### ISSUE TITLE
just wanted to know

### ISSUE THREAD

**Issue by RayTurner345** [qbcore-framework/qb-adminmenu#151]
just wanted to know how to set myself as admin/god to beable to set jobs and etc.

**Comment by Blacky244-dev** [comment]
Currently there is a seemingly a bug with the permissions in qbcore which is why it does not work to add admins manually in the db I myself use txadmin so the owner of the server is thankfully entered as admin I myself noticed it when I wanted to add 2 of my developers, namely when I set them ingame to admin their rights are not saved just as far as info 

here is the link to another one who already told me that
https://github.com/qbcore-framework/qb-adminmenu/issues/148

sorry for my bad english i come from germany

**Comment by FrogCF** [comment]
@RayTurner345 , @Blacky244-dev 

once you done this problem will be fixed. 

Please set yourself like this on the server.cfg 

## Permissions ##

# Resources
add_ace resource.qb-core command allow # Allow qb-core to execute commands

# Gods
add_ace qbcore.god command allow # Allow all commands
add_principal qbcore.god group.admin # Error proof
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

# Inheritance
add_principal identifier.fivem:0000000 qbcore.god #yourname
add_principal identifier.discord:000000000 qbcore.admin #yourname
add_principal identifier.fivem:00000000 qbcore.god #yourname
add_principal identifier.fivem:0000000 qbcore.mod #yourname
add_principal identifier.discord:00000000 qbcore.god #yourname
add_principal identifier.fivem:0000000 qbcore.god #yourname
add_principal identifier.discord:00000000 qbcore.mod #yourname

# Gods
add_ace qbcore.god command allow # Allow all commands

# Inheritance
add_principal qbcore.god group.admin # Allow gods access to the main admin group used to get all default permissions
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

# END OF THE CONFIG!
